name: Build GitHub Pages from Markdown

on:
  push:
    paths:
      - 'data/**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install markdown package
        run: pip install markdown

      - name: Run md_to_html.py script
        run: python md_to_html.py

      - name: Commit generated HTML files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/*.html
          git diff --cached --quiet || git commit -m "Auto-generate HTML pages from markdown"
          git push
